sudo: required
services:
    - docker

before_install:
    - docker build -t lokialice/react-test -f ./client/Dockerfile.dev .
script:
    - docker run lokialice/react-test npm test -- --coverage
after_success:
    - docker build -t lokialice/multi-client ./client
    - docker build -t lokialice/multi-nginx ./nginx
    - docker build -t lokialice/multi-server ./server
    - docker build -t lokialice/multi-worker ./worker
    #Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those image and push them to docker hub
    - docker push lokialice/multi-client
    - docker push lokialice/multi-nginx
    - docker push lokialice/multi-server
    - docker push lokialice/multi-worker